version: '3'

services:

  jenkins:

    container_name: jenkins-servidor-pratica

    image: jenkins-server:5.0

    build:

      context: .

      dockerfile: dockerfileJenkins

    ports:

      - "8081:8080"

    networks:

      - net

  remote_host:

    container_name: remote_ct_host-pratica

    image: remote_im_host:5.0

    build:

      context: .

      dockerfile: dockerfileUbuntu

    networks:

      - net

  remote_web:

    container_name: remote_ct_e-pratica

    image: remote_im_host:0.1

    build:

      context: .

      dockerfile: dockerfileSpring

    ports:

        - 8080:8080

    networks:

      - net
networks:

  net: